// 外部适配器 gRPC 协议。
//
// 拓扑：核心进程只作为 gRPC **Server** 提供 BotService，外部适配器进程作为客户端
// 主动连接核心（监听地址来自适配器配置 adapters.<name>.grpc_addr），并在自己一侧
// 作为 **Server** 提供 AdapterService：
//
//   - BotService：核心实现，适配器调用，用于上行事件（EmitEvent）、读配置、写日志；
//   - AdapterService：外部适配器进程实现，核心主动 dial 后调用，用于初始化、
//     按 bot 实例启停、发送消息与关闭适配器。
//
// 事件方向与外部插件相反：插件的事件由核心 dial 后经 PluginService.HandleEvent
// 推送，适配器的事件由平台推给适配器，再经 BotService.EmitEvent 送进核心。
//
// 本文件与 plugin.proto 同属 package plugin、共用 go_package，并复用其
// Event/Message/Target/Empty/SendResponse 定义，避免同一业务结构出现两份契约。
// 字段命名与 pkg/bot 的 Go 类型一一对应，JSON 载荷统一用「JSON 字符串」承载，
// 以避免 proto 与业务结构体之间的强耦合（业务结构体可独立演进）。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: adapter.proto

package pluginpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdapterService_Init_FullMethodName     = "/plugin.AdapterService/Init"
	AdapterService_Start_FullMethodName    = "/plugin.AdapterService/Start"
	AdapterService_Stop_FullMethodName     = "/plugin.AdapterService/Stop"
	AdapterService_Send_FullMethodName     = "/plugin.AdapterService/Send"
	AdapterService_Shutdown_FullMethodName = "/plugin.AdapterService/Shutdown"
)

// AdapterServiceClient is the client API for AdapterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdapterService 由外部适配器实现，核心 dial 后调用。
type AdapterServiceClient interface {
	// Init 初始化适配器并下发生效配置与令牌，每个进程只调用一次。
	Init(ctx context.Context, in *AdapterInitRequest, opts ...grpc.CallOption) (*AdapterInitResponse, error)
	// Start 启动一个 bot 实例的事件接收，返回该实例的能力声明；
	// 必须已就绪才返回，保证返回后该实例即可产生事件。
	Start(ctx context.Context, in *AdapterInstance, opts ...grpc.CallOption) (*AdapterStartResponse, error)
	// Stop 停止一个 bot 实例，释放该实例独占的资源，必须幂等。
	Stop(ctx context.Context, in *AdapterStopRequest, opts ...grpc.CallOption) (*Empty, error)
	// Send 向平台发送消息，失败原因写在 SendResponse.error 中。
	Send(ctx context.Context, in *AdapterSendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	// Shutdown 通知适配器退出，适配器需停止全部实例、释放资源并尽快返回。
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type adapterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdapterServiceClient(cc grpc.ClientConnInterface) AdapterServiceClient {
	return &adapterServiceClient{cc}
}

func (c *adapterServiceClient) Init(ctx context.Context, in *AdapterInitRequest, opts ...grpc.CallOption) (*AdapterInitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdapterInitResponse)
	err := c.cc.Invoke(ctx, AdapterService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterServiceClient) Start(ctx context.Context, in *AdapterInstance, opts ...grpc.CallOption) (*AdapterStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdapterStartResponse)
	err := c.cc.Invoke(ctx, AdapterService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterServiceClient) Stop(ctx context.Context, in *AdapterStopRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdapterService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterServiceClient) Send(ctx context.Context, in *AdapterSendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, AdapterService_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterServiceClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdapterService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdapterServiceServer is the server API for AdapterService service.
// All implementations must embed UnimplementedAdapterServiceServer
// for forward compatibility.
//
// AdapterService 由外部适配器实现，核心 dial 后调用。
type AdapterServiceServer interface {
	// Init 初始化适配器并下发生效配置与令牌，每个进程只调用一次。
	Init(context.Context, *AdapterInitRequest) (*AdapterInitResponse, error)
	// Start 启动一个 bot 实例的事件接收，返回该实例的能力声明；
	// 必须已就绪才返回，保证返回后该实例即可产生事件。
	Start(context.Context, *AdapterInstance) (*AdapterStartResponse, error)
	// Stop 停止一个 bot 实例，释放该实例独占的资源，必须幂等。
	Stop(context.Context, *AdapterStopRequest) (*Empty, error)
	// Send 向平台发送消息，失败原因写在 SendResponse.error 中。
	Send(context.Context, *AdapterSendRequest) (*SendResponse, error)
	// Shutdown 通知适配器退出，适配器需停止全部实例、释放资源并尽快返回。
	Shutdown(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedAdapterServiceServer()
}

// UnimplementedAdapterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdapterServiceServer struct{}

func (UnimplementedAdapterServiceServer) Init(context.Context, *AdapterInitRequest) (*AdapterInitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedAdapterServiceServer) Start(context.Context, *AdapterInstance) (*AdapterStartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedAdapterServiceServer) Stop(context.Context, *AdapterStopRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedAdapterServiceServer) Send(context.Context, *AdapterSendRequest) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedAdapterServiceServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedAdapterServiceServer) mustEmbedUnimplementedAdapterServiceServer() {}
func (UnimplementedAdapterServiceServer) testEmbeddedByValue()                        {}

// UnsafeAdapterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdapterServiceServer will
// result in compilation errors.
type UnsafeAdapterServiceServer interface {
	mustEmbedUnimplementedAdapterServiceServer()
}

func RegisterAdapterServiceServer(s grpc.ServiceRegistrar, srv AdapterServiceServer) {
	// If the following call panics, it indicates UnimplementedAdapterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdapterService_ServiceDesc, srv)
}

func _AdapterService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdapterInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).Init(ctx, req.(*AdapterInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdapterInstance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).Start(ctx, req.(*AdapterInstance))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdapterStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).Stop(ctx, req.(*AdapterStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdapterSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).Send(ctx, req.(*AdapterSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AdapterService_ServiceDesc is the grpc.ServiceDesc for AdapterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdapterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.AdapterService",
	HandlerType: (*AdapterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _AdapterService_Init_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _AdapterService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _AdapterService_Stop_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _AdapterService_Send_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _AdapterService_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "adapter.proto",
}
