// 外部适配器 gRPC 协议。
//
// 拓扑：核心进程只作为 gRPC **Server** 提供 BotService，外部适配器进程作为客户端
// 主动连接核心（监听地址来自适配器配置 adapters.<name>.grpc_addr），并在自己一侧
// 作为 **Server** 提供 AdapterService：
//
//   - BotService：核心实现，适配器调用，用于上行事件（EmitEvent）、读配置、写日志；
//   - AdapterService：外部适配器进程实现，核心主动 dial 后调用，用于初始化、
//     按 bot 实例启停、发送消息与关闭适配器。
//
// 事件方向与外部插件相反：插件的事件由核心 dial 后经 PluginService.HandleEvent
// 推送，适配器的事件由平台推给适配器，再经 BotService.EmitEvent 送进核心。
//
// 本文件与 plugin.proto 同属 package plugin、共用 go_package，并复用其
// Event/Message/Target/Empty/SendResponse 定义，避免同一业务结构出现两份契约。
// 字段命名与 pkg/bot 的 Go 类型一一对应，JSON 载荷统一用「JSON 字符串」承载，
// 以避免 proto 与业务结构体之间的强耦合（业务结构体可独立演进）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: adapter.proto

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AdapterInfo 是适配器的身份、能力声明与配置键名单。
//
// 双向使用：核心把配置中记录的身份与权限下发给适配器；适配器在
// AdapterInitResponse 中回传自身实际的元信息，核心以回传值为准。
type AdapterInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name 是适配器名，也是配置中 bots[].adapter 的取值。
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version 是适配器版本，仅用于日志与展示。
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// author 是适配器作者，仅用于展示。
	Author string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	// description 是适配器说明，仅用于展示。
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// platforms 是适配器支持的平台名列表。
	Platforms []string `protobuf:"bytes,5,rep,name=platforms,proto3" json:"platforms,omitempty"`
	// permissions 是核心授予该适配器的权限列表，例如 receive_event。
	Permissions []string `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// options 是适配器接受的配置键名单；核心据此对未知配置键告警。
	// 下发给外部适配器时通常为空（外部适配器的配置键由适配器自行声明），
	// 适配器在 AdapterInitResponse 中回传自身实际的键名单。
	Options       []string `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterInfo) Reset() {
	*x = AdapterInfo{}
	mi := &file_adapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterInfo) ProtoMessage() {}

func (x *AdapterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterInfo.ProtoReflect.Descriptor instead.
func (*AdapterInfo) Descriptor() ([]byte, []int) {
	return file_adapter_proto_rawDescGZIP(), []int{0}
}

func (x *AdapterInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdapterInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AdapterInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *AdapterInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdapterInfo) GetPlatforms() []string {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *AdapterInfo) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *AdapterInfo) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// AdapterInitRequest 是核心连接适配器后的初始化参数。
//
// 每个字段都是「核心交给适配器」的信息：适配器名、版本等元信息由核心从配置中
// 读取后下发，令牌、核心地址与进程级配置也由核心注入。一个适配器进程只 Init
// 一次，随后按绑定的 bot 实例逐个 Start。
type AdapterInitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// info 是核心记录的适配器元信息与授予的权限。
	Info *AdapterInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	// token 是核心分配给该适配器的认证令牌，后续 BotService 调用都需携带。
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// core_addr 是核心 BotService 的监听地址，适配器据此反向调用核心。
	CoreAddr string `protobuf:"bytes,3,opt,name=core_addr,json=coreAddr,proto3" json:"core_addr,omitempty"`
	// config_json 是适配器的进程级配置，JSON object 字符串；无配置时为空串。
	ConfigJson    string `protobuf:"bytes,4,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterInitRequest) Reset() {
	*x = AdapterInitRequest{}
	mi := &file_adapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterInitRequest) ProtoMessage() {}

func (x *AdapterInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterInitRequest.ProtoReflect.Descriptor instead.
func (*AdapterInitRequest) Descriptor() ([]byte, []int) {
	return file_adapter_proto_rawDescGZIP(), []int{1}
}

func (x *AdapterInitRequest) GetInfo() *AdapterInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *AdapterInitRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AdapterInitRequest) GetCoreAddr() string {
	if x != nil {
		return x.CoreAddr
	}
	return ""
}

func (x *AdapterInitRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

// AdapterInitResponse 是适配器对初始化的应答。
type AdapterInitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ok 表示适配器是否初始化成功。
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// error 是失败原因，ok 为 true 时为空。
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// info 是适配器回传的实际元信息，核心以它覆盖配置中记录的值。
	Info          *AdapterInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterInitResponse) Reset() {
	*x = AdapterInitResponse{}
	mi := &file_adapter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterInitResponse) ProtoMessage() {}

func (x *AdapterInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterInitResponse.ProtoReflect.Descriptor instead.
func (*AdapterInitResponse) Descriptor() ([]byte, []int) {
	return file_adapter_proto_rawDescGZIP(), []int{2}
}

func (x *AdapterInitResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AdapterInitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AdapterInitResponse) GetInfo() *AdapterInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// AdapterInstance 描述一个要与适配器绑定的 bot 实例，每个实例 Start 一次。
//
// 适配器必须按 bot_id 隔离实例状态，同一进程可服务多个 bot。
type AdapterInstance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bot_id 是机器人实例标识，即配置中的 bots[].name。
	BotId string `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	// platform 是写入 Event.Platform 的平台名。
	Platform string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	// config_json 是该实例的适配器私有配置，JSON object 字符串。
	ConfigJson    string `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterInstance) Reset() {
	*x = AdapterInstance{}
	mi := &file_adapter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterInstance) ProtoMessage() {}

func (x *AdapterInstance) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterInstance.ProtoReflect.Descriptor instead.
func (*AdapterInstance) Descriptor() ([]byte, []int) {
	return file_adapter_proto_rawDescGZIP(), []int{3}
}

func (x *AdapterInstance) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *AdapterInstance) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AdapterInstance) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

// AdapterStartResponse 返回实例启动结果与能力声明。
type AdapterStartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ok 表示该实例是否启动成功。
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// error 是失败原因，ok 为 true 时为空。
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// capabilities 是该实例的能力声明，是核心执行消息段降级的唯一权威来源；
	// 全零按「仅文本」处理并告警。
	Capabilities *Capabilities `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// platform 是该实例实际使用的平台名，优先于 AdapterInstance.platform。
	Platform      string `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterStartResponse) Reset() {
	*x = AdapterStartResponse{}
	mi := &file_adapter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterStartResponse) ProtoMessage() {}

func (x *AdapterStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterStartResponse.ProtoReflect.Descriptor instead.
func (*AdapterStartResponse) Descriptor() ([]byte, []int) {
	return file_adapter_proto_rawDescGZIP(), []int{4}
}

func (x *AdapterStartResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AdapterStartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AdapterStartResponse) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AdapterStartResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

// AdapterStopRequest 是核心停止一个 bot 实例的请求。
type AdapterStopRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bot_id 是要停止的实例标识；Stop 必须幂等。
	BotId         string `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterStopRequest) Reset() {
	*x = AdapterStopRequest{}
	mi := &file_adapter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterStopRequest) ProtoMessage() {}

func (x *AdapterStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterStopRequest.ProtoReflect.Descriptor instead.
func (*AdapterStopRequest) Descriptor() ([]byte, []int) {
	return file_adapter_proto_rawDescGZIP(), []int{5}
}

func (x *AdapterStopRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

// Capabilities 声明平台支持的消息能力，对应 bot.Capabilities。
type Capabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// text 表示支持文本消息段。
	Text bool `protobuf:"varint,1,opt,name=text,proto3" json:"text,omitempty"`
	// markdown 表示支持 Markdown 消息段。
	Markdown bool `protobuf:"varint,2,opt,name=markdown,proto3" json:"markdown,omitempty"`
	// image 表示支持图片消息段。
	Image bool `protobuf:"varint,3,opt,name=image,proto3" json:"image,omitempty"`
	// at 表示支持 @ 消息段。
	At bool `protobuf:"varint,4,opt,name=at,proto3" json:"at,omitempty"`
	// card 表示支持卡片消息段。
	Card bool `protobuf:"varint,5,opt,name=card,proto3" json:"card,omitempty"`
	// file 表示支持文件消息段。
	File bool `protobuf:"varint,6,opt,name=file,proto3" json:"file,omitempty"`
	// reply 表示支持引用回复。
	Reply bool `protobuf:"varint,7,opt,name=reply,proto3" json:"reply,omitempty"`
	// private 表示支持私聊会话。
	Private bool `protobuf:"varint,8,opt,name=private,proto3" json:"private,omitempty"`
	// group 表示支持群聊会话。
	Group         bool `protobuf:"varint,9,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_adapter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_adapter_proto_rawDescGZIP(), []int{6}
}

func (x *Capabilities) GetText() bool {
	if x != nil {
		return x.Text
	}
	return false
}

func (x *Capabilities) GetMarkdown() bool {
	if x != nil {
		return x.Markdown
	}
	return false
}

func (x *Capabilities) GetImage() bool {
	if x != nil {
		return x.Image
	}
	return false
}

func (x *Capabilities) GetAt() bool {
	if x != nil {
		return x.At
	}
	return false
}

func (x *Capabilities) GetCard() bool {
	if x != nil {
		return x.Card
	}
	return false
}

func (x *Capabilities) GetFile() bool {
	if x != nil {
		return x.File
	}
	return false
}

func (x *Capabilities) GetReply() bool {
	if x != nil {
		return x.Reply
	}
	return false
}

func (x *Capabilities) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *Capabilities) GetGroup() bool {
	if x != nil {
		return x.Group
	}
	return false
}

// AdapterSendRequest 是核心请求适配器向平台发送消息，对应 bot.SendRequest。
type AdapterSendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bot_id 指定使用哪个机器人实例发送。
	BotId string `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	// target 是消息接收方。
	Target *Target `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// message 是待发送的统一消息。
	Message *Message `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// reply_to 非空时表示引用回复该消息 ID。
	ReplyTo       string `protobuf:"bytes,4,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterSendRequest) Reset() {
	*x = AdapterSendRequest{}
	mi := &file_adapter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterSendRequest) ProtoMessage() {}

func (x *AdapterSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterSendRequest.ProtoReflect.Descriptor instead.
func (*AdapterSendRequest) Descriptor() ([]byte, []int) {
	return file_adapter_proto_rawDescGZIP(), []int{7}
}

func (x *AdapterSendRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *AdapterSendRequest) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *AdapterSendRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AdapterSendRequest) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

var File_adapter_proto protoreflect.FileDescriptor

const file_adapter_proto_rawDesc = "" +
	"\n" +
	"\radapter.proto\x12\x06plugin\x1a\fplugin.proto\"\xcf\x01\n" +
	"\vAdapterInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\tplatforms\x18\x05 \x03(\tR\tplatforms\x12 \n" +
	"\vpermissions\x18\x06 \x03(\tR\vpermissions\x12\x18\n" +
	"\aoptions\x18\a \x03(\tR\aoptions\"\x91\x01\n" +
	"\x12AdapterInitRequest\x12'\n" +
	"\x04info\x18\x01 \x01(\v2\x13.plugin.AdapterInfoR\x04info\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1b\n" +
	"\tcore_addr\x18\x03 \x01(\tR\bcoreAddr\x12\x1f\n" +
	"\vconfig_json\x18\x04 \x01(\tR\n" +
	"configJson\"d\n" +
	"\x13AdapterInitResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12'\n" +
	"\x04info\x18\x03 \x01(\v2\x13.plugin.AdapterInfoR\x04info\"e\n" +
	"\x0fAdapterInstance\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\tR\n" +
	"configJson\"\x92\x01\n" +
	"\x14AdapterStartResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x128\n" +
	"\fcapabilities\x18\x03 \x01(\v2\x14.plugin.CapabilitiesR\fcapabilities\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\"+\n" +
	"\x12AdapterStopRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\"\xd2\x01\n" +
	"\fCapabilities\x12\x12\n" +
	"\x04text\x18\x01 \x01(\bR\x04text\x12\x1a\n" +
	"\bmarkdown\x18\x02 \x01(\bR\bmarkdown\x12\x14\n" +
	"\x05image\x18\x03 \x01(\bR\x05image\x12\x0e\n" +
	"\x02at\x18\x04 \x01(\bR\x02at\x12\x12\n" +
	"\x04card\x18\x05 \x01(\bR\x04card\x12\x12\n" +
	"\x04file\x18\x06 \x01(\bR\x04file\x12\x14\n" +
	"\x05reply\x18\a \x01(\bR\x05reply\x12\x18\n" +
	"\aprivate\x18\b \x01(\bR\aprivate\x12\x14\n" +
	"\x05group\x18\t \x01(\bR\x05group\"\x99\x01\n" +
	"\x12AdapterSendRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12&\n" +
	"\x06target\x18\x02 \x01(\v2\x0e.plugin.TargetR\x06target\x12)\n" +
	"\amessage\x18\x03 \x01(\v2\x0f.plugin.MessageR\amessage\x12\x19\n" +
	"\breply_to\x18\x04 \x01(\tR\areplyTo2\xa8\x02\n" +
	"\x0eAdapterService\x12?\n" +
	"\x04Init\x12\x1a.plugin.AdapterInitRequest\x1a\x1b.plugin.AdapterInitResponse\x12>\n" +
	"\x05Start\x12\x17.plugin.AdapterInstance\x1a\x1c.plugin.AdapterStartResponse\x121\n" +
	"\x04Stop\x12\x1a.plugin.AdapterStopRequest\x1a\r.plugin.Empty\x128\n" +
	"\x04Send\x12\x1a.plugin.AdapterSendRequest\x1a\x14.plugin.SendResponse\x12(\n" +
	"\bShutdown\x12\r.plugin.Empty\x1a\r.plugin.EmptyB+Z)github.com/RandomLemon/kei/proto/pluginpbb\x06proto3"

var (
	file_adapter_proto_rawDescOnce sync.Once
	file_adapter_proto_rawDescData []byte
)

func file_adapter_proto_rawDescGZIP() []byte {
	file_adapter_proto_rawDescOnce.Do(func() {
		file_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_adapter_proto_rawDesc), len(file_adapter_proto_rawDesc)))
	})
	return file_adapter_proto_rawDescData
}

var file_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_adapter_proto_goTypes = []any{
	(*AdapterInfo)(nil),          // 0: plugin.AdapterInfo
	(*AdapterInitRequest)(nil),   // 1: plugin.AdapterInitRequest
	(*AdapterInitResponse)(nil),  // 2: plugin.AdapterInitResponse
	(*AdapterInstance)(nil),      // 3: plugin.AdapterInstance
	(*AdapterStartResponse)(nil), // 4: plugin.AdapterStartResponse
	(*AdapterStopRequest)(nil),   // 5: plugin.AdapterStopRequest
	(*Capabilities)(nil),         // 6: plugin.Capabilities
	(*AdapterSendRequest)(nil),   // 7: plugin.AdapterSendRequest
	(*Target)(nil),               // 8: plugin.Target
	(*Message)(nil),              // 9: plugin.Message
	(*Empty)(nil),                // 10: plugin.Empty
	(*SendResponse)(nil),         // 11: plugin.SendResponse
}
var file_adapter_proto_depIdxs = []int32{
	0,  // 0: plugin.AdapterInitRequest.info:type_name -> plugin.AdapterInfo
	0,  // 1: plugin.AdapterInitResponse.info:type_name -> plugin.AdapterInfo
	6,  // 2: plugin.AdapterStartResponse.capabilities:type_name -> plugin.Capabilities
	8,  // 3: plugin.AdapterSendRequest.target:type_name -> plugin.Target
	9,  // 4: plugin.AdapterSendRequest.message:type_name -> plugin.Message
	1,  // 5: plugin.AdapterService.Init:input_type -> plugin.AdapterInitRequest
	3,  // 6: plugin.AdapterService.Start:input_type -> plugin.AdapterInstance
	5,  // 7: plugin.AdapterService.Stop:input_type -> plugin.AdapterStopRequest
	7,  // 8: plugin.AdapterService.Send:input_type -> plugin.AdapterSendRequest
	10, // 9: plugin.AdapterService.Shutdown:input_type -> plugin.Empty
	2,  // 10: plugin.AdapterService.Init:output_type -> plugin.AdapterInitResponse
	4,  // 11: plugin.AdapterService.Start:output_type -> plugin.AdapterStartResponse
	10, // 12: plugin.AdapterService.Stop:output_type -> plugin.Empty
	11, // 13: plugin.AdapterService.Send:output_type -> plugin.SendResponse
	10, // 14: plugin.AdapterService.Shutdown:output_type -> plugin.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_adapter_proto_init() }
func file_adapter_proto_init() {
	if File_adapter_proto != nil {
		return
	}
	file_plugin_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_adapter_proto_rawDesc), len(file_adapter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adapter_proto_goTypes,
		DependencyIndexes: file_adapter_proto_depIdxs,
		MessageInfos:      file_adapter_proto_msgTypes,
	}.Build()
	File_adapter_proto = out.File
	file_adapter_proto_goTypes = nil
	file_adapter_proto_depIdxs = nil
}
