// 外部插件 gRPC 协议。
//
// 拓扑：核心进程只作为 gRPC **Server** 提供 BotService，外部插件进程作为客户端
// 主动连接核心（监听地址来自插件配置 plugins.<name>.grpc_addr），并在自己一侧
// 作为 **Server** 提供 PluginService：
//
//   - BotService：核心实现，插件调用，用于发消息、读配置、写日志；
//   - PluginService：外部插件进程实现，核心主动 dial 后调用，用于初始化、
//     投递事件与关闭插件。
//
// 因此本文件中 BotService 的客户端由外部插件使用，PluginService 的客户端由核心
// 的插件加载器使用。字段命名与 pkg/bot 的 Go 类型一一对应，JSON 载荷统一用
// 「JSON 字符串」承载，以避免 proto 与业务结构体之间的强耦合（业务结构体可独立演进）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin.proto

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty 是无字段的占位消息，用于无返回值或无需参数的 RPC。
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

// InitRequest 是核心在连接插件后下发的初始化参数。
//
// 每个字段都是「核心交给插件」的信息，而非插件对自身的描述：插件名、版本等
// 元信息由核心从配置中读取后下发，令牌与配置也由核心注入。
type InitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name 是核心为该插件配置的名称，插件应以它作为自身标识。
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version 是核心记录的插件版本，仅用于日志与展示。
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// author 是核心记录的插件作者，仅用于展示。
	Author string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	// description 是核心记录的插件说明，仅用于展示。
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// permissions 是核心授予该插件的权限列表。
	Permissions []string `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// config_json 是核心下发的该插件配置，JSON object 字符串；无配置时为空串。
	ConfigJson string `protobuf:"bytes,6,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	// token 是核心分配给该插件的认证令牌，后续 BotService 调用都需携带。
	Token string `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	// reply_service_addr 是核心 BotService 的监听地址，插件据此反向调用核心。
	ReplyServiceAddr string `protobuf:"bytes,8,opt,name=reply_service_addr,json=replyServiceAddr,proto3" json:"reply_service_addr,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *InitRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InitRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *InitRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InitRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *InitRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *InitRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *InitRequest) GetReplyServiceAddr() string {
	if x != nil {
		return x.ReplyServiceAddr
	}
	return ""
}

// InitResponse 是插件对初始化的应答。
type InitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ok 表示插件是否初始化成功。
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// error 是失败原因，ok 为 true 时为空。
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *InitResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *InitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Event 是核心投递给插件的平台无关事件，对应 bot.Event。
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 是事件唯一标识，用于去重。
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// type 是事件分类：message/notice/request/meta。
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// platform 是产生事件的平台名，与适配器名一致。
	Platform string `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	// bot_id 是接收该事件的机器人标识。
	BotId string `protobuf:"bytes,4,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	// time_unix_ms 是事件发生时间，Unix 毫秒（UTC）。
	TimeUnixMs int64 `protobuf:"varint,5,opt,name=time_unix_ms,json=timeUnixMs,proto3" json:"time_unix_ms,omitempty"`
	// message 是消息内容，仅在 type 为 message 时存在。
	Message *Message `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	// sender 是消息发送者，可能缺省。
	Sender *User `protobuf:"bytes,7,opt,name=sender,proto3" json:"sender,omitempty"`
	// channel 是消息所在会话，私聊时可能缺省。
	Channel *Channel `protobuf:"bytes,8,opt,name=channel,proto3" json:"channel,omitempty"`
	// command 是解析后的命令，未触发命令时缺省。
	Command *Command `protobuf:"bytes,9,opt,name=command,proto3" json:"command,omitempty"`
	// raw_json 是平台原始事件，JSON 字符串，仅用于调试。
	RawJson       string `protobuf:"bytes,10,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Event) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *Event) GetTimeUnixMs() int64 {
	if x != nil {
		return x.TimeUnixMs
	}
	return 0
}

func (x *Event) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Event) GetSender() *User {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Event) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *Event) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Event) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

// Message 是平台无关的消息，对应 bot.Message。
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 是消息 ID，发送前可为空。
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// kind 是会话类型：private/group/channel。
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// segments 是按顺序排列的消息段。
	Segments      []*Segment `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Message) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

// Segment 是消息的一个片段，对应 bot.Segment。
type Segment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type 是片段类型：text/image/at/face/reply/markdown/card/file。
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// data_json 是片段数据，JSON object 字符串，键名见 pkg/bot 的 Key* 常量。
	DataJson      string `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *Segment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Segment) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

// User 是消息发送者或 @ 的目标用户，对应 bot.User。
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 是平台内的用户唯一标识。
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name 是用户显示名。
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// is_bot 表示该用户是否为机器人。
	IsBot         bool `protobuf:"varint,3,opt,name=is_bot,json=isBot,proto3" json:"is_bot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetIsBot() bool {
	if x != nil {
		return x.IsBot
	}
	return false
}

// Channel 是消息所在的会话，对应 bot.Channel。
type Channel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 是平台内的会话唯一标识。
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name 是会话显示名。
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// kind 是会话类型：private/group/channel。
	Kind          string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *Channel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// Command 是解析后的命令，对应 bot.Command。
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name 是命令名，不含前缀。
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// args 是命令参数，保持原样不做拆分。
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// raw 是命令的原始文本。
	Raw           string `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *Command) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Command) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Command) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

// HandleResult 是插件处理事件的应答。
type HandleResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// handled 表示插件是否消费了该事件。
	Handled bool `protobuf:"varint,1,opt,name=handled,proto3" json:"handled,omitempty"`
	// error 是处理失败原因，成功时为空。
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleResult) Reset() {
	*x = HandleResult{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleResult) ProtoMessage() {}

func (x *HandleResult) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleResult.ProtoReflect.Descriptor instead.
func (*HandleResult) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *HandleResult) GetHandled() bool {
	if x != nil {
		return x.Handled
	}
	return false
}

func (x *HandleResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SendRequest 是插件请求核心发送消息的请求。
type SendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token 是插件在 Init 阶段获得的认证令牌，必填。
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// target 是消息接收方。
	Target *Target `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// message 是待发送的统一消息。
	Message *Message `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// reply_to 非空时表示引用回复该消息 ID。
	ReplyTo       string `protobuf:"bytes,4,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *SendRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SendRequest) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *SendRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SendRequest) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

// Target 描述消息接收方，对应 bot.Target。
type Target struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// platform 是平台名。
	Platform string `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	// channel_id 是群/频道 ID，私聊时可为空。
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// user_id 是用户 ID，群聊时可为空。
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// kind 是会话类型：private/group/channel。
	Kind string `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	// bot_id 是机器人标识（核心配置中的 bot 名称）；为空时由核心按平台自动选择
	// （该平台只有一个 bot 时可用），同平台多个 bot 时必须显式指定。
	BotId         string `protobuf:"bytes,5,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *Target) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Target) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Target) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Target) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Target) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

// SendResponse 是发送结果的应答。
type SendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_id 是平台返回的消息 ID，发送失败时为空。
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// error 是发送失败原因，成功时为空。
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *SendResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetConfigRequest 是插件读取自身配置的请求。
type GetConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token 是插件令牌，必填。
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// key 是配置键，支持 "a.b.c" 多级路径；为空表示读取整份配置。
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *GetConfigRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetConfigResponse 是配置读取的应答。
type GetConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// found 表示配置或键是否存在。
	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// value_json 是配置值的 JSON 字符串，found 为 false 时为空。
	ValueJson     string `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *GetConfigResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetConfigResponse) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

// LogRequest 是插件写入核心日志的请求。
type LogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token 是插件令牌，必填。
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// level 是日志级别：debug/info/warn/error，未知取值按 info 处理。
	Level string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	// message 是日志正文。
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// fields_json 是结构化字段，JSON object 字符串。
	FieldsJson    string `protobuf:"bytes,4,opt,name=fields_json,json=fieldsJson,proto3" json:"fields_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *LogRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRequest) GetFieldsJson() string {
	if x != nil {
		return x.FieldsJson
	}
	return ""
}

// EmitEventRequest 是外部适配器向核心投递平台事件的请求。
//
// 该 RPC 只供外部适配器使用：外部插件的事件流向相反，由核心经 PluginService.
// HandleEvent 投递。适配器必须先 ACK 平台，再调用本 RPC。
type EmitEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token 是适配器在 Init 阶段获得的认证令牌，必填。
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// event 是待投递的平台无关事件；为空视为参数非法。
	Event         *Event `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitEventRequest) Reset() {
	*x = EmitEventRequest{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitEventRequest) ProtoMessage() {}

func (x *EmitEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitEventRequest.ProtoReflect.Descriptor instead.
func (*EmitEventRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *EmitEventRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EmitEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// EmitEventResponse 是事件投递的应答。
type EmitEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ok 表示事件是否已入队，不表示已被处理或已被插件消费。
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// error 是入队失败原因，ok 为 true 时为空。
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitEventResponse) Reset() {
	*x = EmitEventResponse{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitEventResponse) ProtoMessage() {}

func (x *EmitEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitEventResponse.ProtoReflect.Descriptor instead.
func (*EmitEventResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *EmitEventResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *EmitEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x06plugin\"\a\n" +
	"\x05Empty\"\xfc\x01\n" +
	"\vInitRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x12\x1f\n" +
	"\vconfig_json\x18\x06 \x01(\tR\n" +
	"configJson\x12\x14\n" +
	"\x05token\x18\a \x01(\tR\x05token\x12,\n" +
	"\x12reply_service_addr\x18\b \x01(\tR\x10replyServiceAddr\"4\n" +
	"\fInitResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xc2\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x15\n" +
	"\x06bot_id\x18\x04 \x01(\tR\x05botId\x12 \n" +
	"\ftime_unix_ms\x18\x05 \x01(\x03R\n" +
	"timeUnixMs\x12)\n" +
	"\amessage\x18\x06 \x01(\v2\x0f.plugin.MessageR\amessage\x12$\n" +
	"\x06sender\x18\a \x01(\v2\f.plugin.UserR\x06sender\x12)\n" +
	"\achannel\x18\b \x01(\v2\x0f.plugin.ChannelR\achannel\x12)\n" +
	"\acommand\x18\t \x01(\v2\x0f.plugin.CommandR\acommand\x12\x19\n" +
	"\braw_json\x18\n" +
	" \x01(\tR\arawJson\"Z\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12+\n" +
	"\bsegments\x18\x03 \x03(\v2\x0f.plugin.SegmentR\bsegments\":\n" +
	"\aSegment\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\tR\bdataJson\"A\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_bot\x18\x03 \x01(\bR\x05isBot\"A\n" +
	"\aChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\"C\n" +
	"\aCommand\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x10\n" +
	"\x03raw\x18\x03 \x01(\tR\x03raw\">\n" +
	"\fHandleResult\x12\x18\n" +
	"\ahandled\x18\x01 \x01(\bR\ahandled\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x91\x01\n" +
	"\vSendRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12&\n" +
	"\x06target\x18\x02 \x01(\v2\x0e.plugin.TargetR\x06target\x12)\n" +
	"\amessage\x18\x03 \x01(\v2\x0f.plugin.MessageR\amessage\x12\x19\n" +
	"\breply_to\x18\x04 \x01(\tR\areplyTo\"\x87\x01\n" +
	"\x06Target\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x15\n" +
	"\x06bot_id\x18\x05 \x01(\tR\x05botId\"C\n" +
	"\fSendResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\":\n" +
	"\x10GetConfigRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"H\n" +
	"\x11GetConfigResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\tR\tvalueJson\"s\n" +
	"\n" +
	"LogRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vfields_json\x18\x04 \x01(\tR\n" +
	"fieldsJson\"M\n" +
	"\x10EmitEventRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\x05event\x18\x02 \x01(\v2\r.plugin.EventR\x05event\"9\n" +
	"\x11EmitEventResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xa0\x01\n" +
	"\rPluginService\x121\n" +
	"\x04Init\x12\x13.plugin.InitRequest\x1a\x14.plugin.InitResponse\x122\n" +
	"\vHandleEvent\x12\r.plugin.Event\x1a\x14.plugin.HandleResult\x12(\n" +
	"\bShutdown\x12\r.plugin.Empty\x1a\r.plugin.Empty2\xf4\x01\n" +
	"\n" +
	"BotService\x128\n" +
	"\vSendMessage\x12\x13.plugin.SendRequest\x1a\x14.plugin.SendResponse\x12@\n" +
	"\tGetConfig\x12\x18.plugin.GetConfigRequest\x1a\x19.plugin.GetConfigResponse\x12(\n" +
	"\x03Log\x12\x12.plugin.LogRequest\x1a\r.plugin.Empty\x12@\n" +
	"\tEmitEvent\x12\x18.plugin.EmitEventRequest\x1a\x19.plugin.EmitEventResponseB+Z)github.com/RandomLemon/kei/proto/pluginpbb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_plugin_proto_goTypes = []any{
	(*Empty)(nil),             // 0: plugin.Empty
	(*InitRequest)(nil),       // 1: plugin.InitRequest
	(*InitResponse)(nil),      // 2: plugin.InitResponse
	(*Event)(nil),             // 3: plugin.Event
	(*Message)(nil),           // 4: plugin.Message
	(*Segment)(nil),           // 5: plugin.Segment
	(*User)(nil),              // 6: plugin.User
	(*Channel)(nil),           // 7: plugin.Channel
	(*Command)(nil),           // 8: plugin.Command
	(*HandleResult)(nil),      // 9: plugin.HandleResult
	(*SendRequest)(nil),       // 10: plugin.SendRequest
	(*Target)(nil),            // 11: plugin.Target
	(*SendResponse)(nil),      // 12: plugin.SendResponse
	(*GetConfigRequest)(nil),  // 13: plugin.GetConfigRequest
	(*GetConfigResponse)(nil), // 14: plugin.GetConfigResponse
	(*LogRequest)(nil),        // 15: plugin.LogRequest
	(*EmitEventRequest)(nil),  // 16: plugin.EmitEventRequest
	(*EmitEventResponse)(nil), // 17: plugin.EmitEventResponse
}
var file_plugin_proto_depIdxs = []int32{
	4,  // 0: plugin.Event.message:type_name -> plugin.Message
	6,  // 1: plugin.Event.sender:type_name -> plugin.User
	7,  // 2: plugin.Event.channel:type_name -> plugin.Channel
	8,  // 3: plugin.Event.command:type_name -> plugin.Command
	5,  // 4: plugin.Message.segments:type_name -> plugin.Segment
	11, // 5: plugin.SendRequest.target:type_name -> plugin.Target
	4,  // 6: plugin.SendRequest.message:type_name -> plugin.Message
	3,  // 7: plugin.EmitEventRequest.event:type_name -> plugin.Event
	1,  // 8: plugin.PluginService.Init:input_type -> plugin.InitRequest
	3,  // 9: plugin.PluginService.HandleEvent:input_type -> plugin.Event
	0,  // 10: plugin.PluginService.Shutdown:input_type -> plugin.Empty
	10, // 11: plugin.BotService.SendMessage:input_type -> plugin.SendRequest
	13, // 12: plugin.BotService.GetConfig:input_type -> plugin.GetConfigRequest
	15, // 13: plugin.BotService.Log:input_type -> plugin.LogRequest
	16, // 14: plugin.BotService.EmitEvent:input_type -> plugin.EmitEventRequest
	2,  // 15: plugin.PluginService.Init:output_type -> plugin.InitResponse
	9,  // 16: plugin.PluginService.HandleEvent:output_type -> plugin.HandleResult
	0,  // 17: plugin.PluginService.Shutdown:output_type -> plugin.Empty
	12, // 18: plugin.BotService.SendMessage:output_type -> plugin.SendResponse
	14, // 19: plugin.BotService.GetConfig:output_type -> plugin.GetConfigResponse
	0,  // 20: plugin.BotService.Log:output_type -> plugin.Empty
	17, // 21: plugin.BotService.EmitEvent:output_type -> plugin.EmitEventResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
